server:
  port: 9000


spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/werewolf?serverTimezone=Asia/Shanghai&useUnicode=true&useSSL=false&autoReconnect=true
    username: root
    password: erongdu.com
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
#    druid:
#      filters: stat,log4j
#      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

mybatis:
  mapper-locations: mapper/*.xml
